language: python
python:
  - 2.6
install: 
  # Supposed to help get PIL to install on PyPi
  # https://github.com/python-imaging/Pillow/issues/570
  - sudo apt-get install python-tk
  # Install external filter binaries
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get install npm rubygems
  - # Use non-https registry? https://github.com/n1k0/casperjs/issues/876
  - sudo npm config set registry http://registry.npmjs.org/
  - sh requirements-dev.sh
  - pip install tox
script: tox
notifications:
  email:
    - michael@elsdoerfer.com
branches:
  only:
    - master

matrix:
  allow_failures:
    # Can't get PyPy to build so far.
    - python: "pypy"
